version: '3'

networks:
  gslab:

services:
  web_server:
    image: my_server:latest
    networks:
      - gslab
    ports:
      - 80:80
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.1'
          memory: '50M'
  # 2nd part
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports: [ "81:8080" ]
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
