version: "3"  # docker-compose version
services:     # list all services for your application

  visualizer:
    image: dockersamples/visualizer:stable
    ports: [ "8080:8080" ]
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager

  users-db:
    image: rahmjan/users-db
    build: ../users/src/db
    ports: [ "6000:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  users-daemon:
    image: rahmjan/users-daemon
    build: ../users
    depends_on: [ "users-db" ]
    ports: [ "1000:80" ]
    deploy:
      replicas: 1

  catalog:
    image: rahmjan/catalog
    build: ../catalog
    depends_on: [ "catalog-db" ]
    ports: [ "1001:80" ]
    deploy:
      replicas: 1

  catalog-db:
    image: rahmjan/catalog-db
    build: ../catalog/src/db
    ports: [ "6001:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  shopping_cart:
    image: rahmjan/shopping_cart
    build: ../shopping_cart
    depends_on: [ "shopping_cart-db" ]
    ports: [ "1002:80" ]
    deploy:
      replicas: 1

  shopping_cart-db:
    image: rahmjan/shopping_cart-db
    build: ../shopping_cart/src/db
    ports: [ "6002:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  purchase:
    image: rahmjan/purchase
    build: ../purchase
    depends_on: [ "purchase-db" ]
    ports: [ "1003:80" ]
    deploy:
      replicas: 1

  purchase-db:
    image: rahmjan/purchase-db
    build: ../purchase/src/db
    ports: [ "6003:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  logging:
    image: rahmjan/logging
    build: ../logging
    depends_on: [ "logging-db" ]
    ports: [ "1004:80" ]
    deploy:
      replicas: 1

  logging-db:
    image: rahmjan/logging-db
    build: ../logging/src/db
    ports: [ "6004:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  recomm:
    image: rahmjan/recomm
    build: ../recomm
    depends_on: [ "logging-db" ]
    ports: [ "1005:80" ]
    deploy:
      replicas: 1

  recomm-db:
    image: rahmjan/recomm-db
    build: ../recomm/src/db
    ports: [ "6005:5984" ]
    logging:
      driver: "none"
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure


